from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class IComparable(Protocol):
    def __gt__(self, other : Any, /) -> bool: ...
    def __ge__(self, other : Any, /) -> bool: ...
    def __lt__(self, other : Any, /) -> bool: ...
    def __le__(self, other : Any, /) -> bool: ...
