from enum import Enum
from typing import TYPE_CHECKING, Any

class OrderedEnum(Enum):
    if TYPE_CHECKING: # pragma: no cover
        def __gt__(self, other: Any, /) -> bool: ...
        def __ge__(self, other: Any, /) -> bool: ...
        def __lt__(self, other: Any, /) -> bool: ...
        def __le__(self, other: Any, /) -> bool: ...
